# Use an official Node runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Vue project
# RUN npm run build

# Expose the port the app runs on
EXPOSE 9000

# Define environment variable
ENV NODE_ENV=production

# Command to run the application
CMD ["npm", "run", "dev"]
